# Generated by Django 5.1.1 on 2024-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_booking_meeting_link'),
        ('industry', '0002_expertise_expertise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='mentees', to='industry.expertise'),
        ),
    ]
