# Generated by Django 5.1.1 on 2024-10-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customuser_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='bio',
            new_name='short_intro',
        ),
    ]
