# Generated by Django 5.1.1 on 2024-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_bio_mentor_short_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wallet_payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
