# Generated by Django 5.1.1 on 2024-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_booking_wallet_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='wallet_payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
