# Generated by Django 5.1.1 on 2024-10-06 12:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0012_teammates_linkedinurl_teammates_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicypage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
