# Generated by Django 5.1.1 on 2024-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionsetting',
            name='value',
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
    ]
