# Generated by Django 5.1.1 on 2024-11-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_booking_wallet_payment_status'),
        ('paybook', '0002_remove_commissionsetting_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsetting',
            name='minimum_payout',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.mentor')),
            ],
        ),
    ]
