# Generated by Django 5.1.1 on 2024-11-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0154_alter_cohort_end_date_alter_cohort_start_date'),
        ('cohorts', '0155_populate_slug_field'),
    ]

    operations = [
    ]
